name: Statiq Site Update

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive' # Theme in a submodule

      - name: Manually Update SubModules
        run: git submodule update --init --recursive

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Build with Statiq
        run: dotnet run
        env:
          GITHUB_TOKEN: ${{ secrets.GOOGLEAPIKEY }}

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './output'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
